### ISSUE TITLE
Running the Bundle Install Resource with a Cron Task

### ISSUE THREAD

**Issue by mgm702** [poise/poise-ruby#14]
Hello, 

I'm trying to use the bundle_install resource inside a cron job that calls chef-client for updating my application server. The only problem is that when I get to this point I receive the following error:

```
#<TypeError: application_bundle_install[/home/deploy/projects/app/] (app_deploy::default line 30) had an error: TypeError: no implicit conversion of false into String> had an error:
application_bundle_install[/home/deploy/projects/app/] (app_deploy::default line 30) had an error: TypeError: no implicit conversion of false into String
Description: Error executing action `install` on resource 'application_bundle_install[/home/deploy/projects/app/]'
```

**Here is the cookbook stacktrace:**

```
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:46:in `split'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:46:in `default_gem_binary'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:34:in `block in <module:Resource>'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/lazy_default.rb:57:in `set_or_return'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/win32_user.rb:60:in `set_or_return'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/lwrp_polyfill.rb:114:in `block in attribute'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:177:in `poise_gem_bindir'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:131:in `bundler_binary'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:219:in `bundler_command'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:160:in `run_bundler'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:119:in `action_install'
```

**Here's my resource declaration:**

```
# In /var/chef/cache/cookbooks/app_deploy/recipes/default.rb

 30:   bundle_install do
 31:     path "#{app_path}/"
 32:     user 'deploy'
 33:   end
 34: end
```

**Here's my compiled resource:**

```
# Declared in /var/chef/cache/cookbooks/app_deploy/recipes/default.rb:30:in `block in from_file'

application_bundle_install("/home/deploy/projects/app/") do
  action [:install]
  default_guard_interpreter :default
  declared_type :application_bundle_install
  cookbook_name "app_deploy"
  recipe_name "default"
  parent application[/home/deploy/projects/app/]
  path "/home/deploy/projects/app/"
  user "deploy"
  parent_ruby nil
end
```

**And finally my full stacktrace is:**

```
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:46:in `split'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:46:in `default_gem_binary'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_command_mixin.rb:34:in `block in <module:Resource>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/property.rb:648:in `instance_exec'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/property.rb:648:in `exec_in_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/property.rb:666:in `stored_value_to_output'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/property.rb:352:in `get'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/params_validate.rb:471:in `get'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/params_validate.rb:482:in `call'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/mixin/params_validate.rb:123:in `set_or_return'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/lazy_default.rb:57:in `set_or_return'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/win32_user.rb:60:in `set_or_return'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/lwrp_polyfill.rb:114:in `block in attribute'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:177:in `poise_gem_bindir'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:131:in `bundler_binary'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:219:in `bundler_command'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:160:in `run_bundler'
/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/bundle_install.rb:119:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:171:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:715:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:749:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

Any help with this issue is greatly appreciated, I look forward to your response!

**Comment by coderanger** [comment]
Are you sure you are installing Ruby correctly? Please include the full recipe.

**Comment by mgm702** [comment]
Ruby is installed system-wide as is bundler. 

The recipe doesn't install ruby or bundler, but here is the full recipe:

```
#
# Cookbook:: app_deploy
# Recipe:: default
#
# Copyright:: 2017, The Authors, All Rights Reserved.

app_path = "/home/deploy/projects/app"

git "#{app_path}" do
   repository 'git@gitlab.com/app.git'
   revision 'master'
   user 'deploy'
   group 'aljex'
   action :sync
end

# replace passenger gem with puma in Gemfile
ruby_block "Replace Passenger gem" do
  block do
    fe = Chef::Util::FileEdit.new("#{app_path}/Gemfile")
    fe.search_file_replace_line(/^(gem 'passenger'*)/, "gem 'puma'")
    fe.write_file
  end
  only_if{ ::File.readlines("#{app_path}/Gemfile").grep(/^(gem 'passenger')/).any? }
end

# - run bundle install on the app directory
application "#{app_path}/" do
  bundle_install do
    path "#{app_path}/"
    user 'deploy'
  end
end

# - move database.yml template file into project directory (replacing one currently in there)
cookbook_file "#{app_path}/config/database.yml" do
  source 'database.yml'
  owner 'deploy'
  group 'aljex'
  mode '0755'
  action :create
end
```

**Comment by coderanger** [comment]
How is it installed system-wide? That error is because from inside the cronjob, there is no `ruby` executable on `$PATH`. This is usually because you installed Ruby to a non-standard location of some kind and then updated `$PATH` in a shell `rc` file which doesn't affect cron or other services. You can give Chef the path manually by adding this:

```ruby
application app_path do
  ruby do
    provider :dummy
    options ruby_binary: "/path/to/ruby"
  end

  bundle_install do
    path app_path
    user 'deploy'
  end

  # Pro-tip, if you use `cookbook_file` or `template` inside the application block, relative paths are handled for you.
  cookbook_file "config/database.yml" do
    source 'database.yml'
    owner 'deploy'
    group 'aljex'
    mode '0755'
  end
end
```

Note that this won't work for SCL packages since they are special, if using that you'll need to use the actual `:scl` provider.

**Comment by mgm702** [comment]
Thank you so much I think this fixed my problem with bundle_install! I really appreciate the quick response it helped me out so much. Great cookbook by the way I look forward to using it more in my server configuration/setup. 

Have a great rest of your day!
