### ISSUE TITLE
poise-ruby fails during compile

### ISSUE THREAD

**Issue by jdblack** [poise/poise-ruby#7]
[root@ip-10-10-0-79 instance]# chef-client -r XXXXXX::appserver_role -E develop
Starting Chef Client, version 12.4.0
resolving cookbooks for run list: ["XXXXXX::appserver_role"]
Synchronizing Cookbooks:
  - XXXXXX
  - poise-ruby
  - poise
  - yum
  - sudo
  - ssh-keys
  - users
  - chef-client
  - apt
  - chef_handler
  - windows
  - logrotate
  - application_ruby
  - application
  - unicorn
  - cron
  - gluster
  - apache2
  - freebsd
  - passenger_apache2
  - pacman
  - iptables
  - runit
  - build-essential
  - packagecloud
Compiling Cookbooks...

==========================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/poise-ruby/libraries/poise_ruby.rb
==========================================================================

NameError
---------
uninitialized constant Chef::Resource::PoiseRuby::Poise

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise-ruby/libraries/poise_ruby.rb:21:in `<class:PoiseRuby>'
  /var/chef/cache/cookbooks/poise-ruby/libraries/poise_ruby.rb:20:in `<class:Chef>'
  /var/chef/cache/cookbooks/poise-ruby/libraries/poise_ruby.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise-ruby/libraries/poise_ruby.rb:

 14:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 15:  # See the License for the specific language governing permissions and
 16:  # limitations under the License.
 17:  #
 18:  
 19:  class Chef
 20:    class Resource::PoiseRuby < Resource
 21>>     include Poise
 22:      actions(:upgrade, :install, :remove)
 23:  
 24:      attribute(:flavor, name_attribute: true)
 25:      attribute(:version, kind_of: String)
 26:  
 27:      def package_name
 28:        "poise-#{flavor}"
 29:      end
 30:    end

Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 2.740744467 seconds

------------------------------------------------------------------------------------------------
The recipe itself looks like this:

==================== XXXXXX::appserver_role
include_recipe "XXXXXX::base_role"
ruby_runtime '1.8.7'

%w[mysql-devel GeoIP GeoIP-devel zlib-devel].each do |p|
  package p
end

user 'XXXXXX''
include_recipe "XXXXXX::deploy_app"

**Comment by jdblack** [comment]
Never mind.  berkfile pulled down an old version of poise-ruby.
